---
- hosts: all
  gather_facts: no
  tasks:
    - name: Wait 600 seconds for target connection to become reachable/usable
      wait_for_connection:

- hosts: all
  tasks:
    - name: Add Apt signing key
      become: true
      apt_key:
        url: https://neilalexander.s3.dualstack.eu-west-2.amazonaws.com/deb/key.txt
        state: present

    - name: Enable Apt repository
      become: true
      apt_repository:
        repo: deb http://neilalexander.s3.dualstack.eu-west-2.amazonaws.com/deb/ debian yggdrasil
        state: present

    - name: Install yggdrasil
      become: true
      package:
        update_cache: true
        name: yggdrasil
        state: latest

- hosts: vms
  handlers:
    - name: restart yggdrasil
      become: true
      service:
        name: yggdrasil
        state: restarted
  tasks:
    - name: Edit yggdrasil config
      become: true
      replace:
        path: /etc/yggdrasil.conf
        regexp: 'Peers: \[\]'
        replace: 'Peers: ["tls://{{ registry_ip }}:12345"]'
      notify: restart yggdrasil

- hosts: registry
  handlers:
    - name: restart yggdrasil
      become: true
      service:
        name: yggdrasil
        state: restarted
  tasks:
    - name: Edit yggdrasil config
      become: true
      replace:
        path: /etc/yggdrasil.conf
        regexp: 'Listen: \[\]'
        replace: 'Listen: ["tls://0.0.0.0:12345"]'
      notify: restart yggdrasil

